spring.application.name=url-shortner
server.port=8082

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ugxwrmkmdxzkomcpveol
spring.datasource.password=uYTOGRTqSacaGKE0
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.short-base-url=http://localhost:8082/r
app.cors.allowed-origins=http://localhost:3000

logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.web=INFO