spring.application.name=url-shortner
server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL:jdbc:postgresql://db.ugxwrmkmdxzkomcpveol.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:supabaseadmin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:10}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:5}
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.short-base-url=${APP_SHORT_BASE_URL:http://localhost:8082/r}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.web=INFO